### ISSUE TITLE
`defineRoute` codemod checklist

### ISSUE THREAD

**Issue by KubaJastrz** [KubaJastrz/typesafe-remix-codemod#2]
## `defineRoute`

> Upstream development in https://github.com/remix-run/react-router/pull/11596

- [ ] Move all known exports into `defineRoute` default export
	- [x] Default export -> `Component`
		- [x] Function component
		- [ ] Class component (it this even supported by Remix?)
		- [x] Remove `useLoaderData` and inject `loaderData` param ([code](https://github.com/remix-run/react-router/blob/eef81c9cc8555f4f7e0881cfbdb18ddfaf9caaa5/packages/react-router/lib/router/define-route.test.ts#L73))
		- [x] Remove `useActionData` and inject `actionData` param ([code](https://github.com/remix-run/react-router/blob/eef81c9cc8555f4f7e0881cfbdb18ddfaf9caaa5/packages/react-router/lib/router/define-route.test.ts#L228)) 
		- [ ] Add `params` param? Not sure if needed in the codemod, as components in the old code didn't have access to this ([source](https://x.com/pcattori/status/1798355710968844784))
		- [ ] Do something about `useFetcher<typeof action>` ([example](https://github.com/epicweb-dev/epic-stack/blob/3649cb9217084ed57055c76f237289525b252e2f/app/routes/_auth%2B/forgot-password.tsx#L121))
	- [x] Named exports = everything else (keep unknown export untouched)
		- [x] `loader` -> `serverLoader`
		- [x] `clientLoader`
		- [x] `action` -> `serverAction`
		- [x] `clientAction`
		- [x] `meta`
			- [ ] rename argument `data` -> `loaderData` ([code](https://github.com/remix-run/react-router/blob/eef81c9cc8555f4f7e0881cfbdb18ddfaf9caaa5/packages/react-router/lib/router/define-route.test.ts#L78))
		- [x] `links`
		- [x] `ErrorBoundary`
		- [x] `HydrateFallback`
		- [ ] `headers` - deprecated in Single Fetch
		- [ ] `handle` - likely unsupported by `defineRoute`
		- [x] Remove all type annotation in function arguments (like `LoaderFunctionArgs`)
- [ ] Order all exports based on the predefined order ([to satisfy TS generics](https://x.com/pcattori/status/1800538393342021750))
- [ ] #4
- [x] Add `clientLoaderHydrate` field ([code](https://github.com/remix-run/react-router/blob/eef81c9cc8555f4f7e0881cfbdb18ddfaf9caaa5/packages/react-router/lib/router/define-route.test.ts#L199))
- [ ] Special handling for `defineRootRoute` ([code](https://github.com/remix-run/react-router/blob/eef81c9cc8555f4f7e0881cfbdb18ddfaf9caaa5/packages/react-router/lib/router/define-route.ts#L206))

Other:
- [x] Find all route files with `npx remix routes --json`
- [ ] Read `app` from config somehow, it is hardcoded for now
- [ ] Add import for `defineRoute`
- [ ] Remove all unnecessary imports?
- [ ] Package into something executable by `npx`
- [ ] Warn about non-standard use of `typeof loader`/`typeof action` ([example](https://github.com/epicweb-dev/epic-stack/blob/3649cb9217084ed57055c76f237289525b252e2f/app/routes/settings%2B/profile.connections.tsx#L165))
- [ ] Detect indentation (tabs vs spaces, length of spaces)
- [ ] Support experimental `unstable_defineAction` and `unstable_defineLoader`?

Bugs:
- [x] #3
